# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_modal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(629, 475)
        Dialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.plotLayout = QtWidgets.QVBoxLayout(self.widget)
        self.plotLayout.setObjectName("plotLayout")
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.plotLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.plotLayout_2.setObjectName("plotLayout_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_message_buttons = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_message_buttons.sizePolicy().hasHeightForWidth())
        self.widget_message_buttons.setSizePolicy(sizePolicy)
        self.widget_message_buttons.setObjectName("widget_message_buttons")
        self.layout_message_buttons = QtWidgets.QHBoxLayout(self.widget_message_buttons)
        self.layout_message_buttons.setObjectName("layout_message_buttons")
        self.pushButton = QtWidgets.QPushButton(self.widget_message_buttons)
        self.pushButton.setObjectName("pushButton")
        self.layout_message_buttons.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget_message_buttons)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "PushButton"))
