# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_modal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog_convert_graphics_to_values(object):
    def setupUi(self, dialog_convert_graphics_to_values):
        dialog_convert_graphics_to_values.setObjectName("dialog_convert_graphics_to_values")
        dialog_convert_graphics_to_values.resize(680, 541)
        dialog_convert_graphics_to_values.setModal(True)
        self.layout_dialog = QtWidgets.QVBoxLayout(dialog_convert_graphics_to_values)
        self.layout_dialog.setContentsMargins(0, 0, 0, 0)
        self.layout_dialog.setSpacing(0)
        self.layout_dialog.setObjectName("layout_dialog")
        self.widget_design = QtWidgets.QWidget(dialog_convert_graphics_to_values)
        self.widget_design.setStyleSheet("QWidget{\n"
"    background-color: rgb(33, 37, 43);\n"
"    color: rgb(208, 208, 208);\n"
"    font-size: 10pt;\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
" QScrollBar {\n"
"border: none;                                                /* без границ */\n"
"    border-right:5px solid rgb(211, 211, 211);;    /* С правой красной раницей */\n"
" }\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
"/* Ползунок */\n"
" QScrollBar::handle:vertical {    \n"
"    background:rgb(255, 255, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
"/*Нижняя стрелка*/\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/*Верхняя стрелка*/\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"/* Цвета нижних и верхних стрелок */\n"
" QScrollBar::up-arrow:vertical{\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
" }\n"
"QScrollBar::down-arrow:vertical{\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     background: rgb(255, 255, 255);\n"
"}\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(255, 255, 255);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QRadioButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"}\n"
"/* срабатывает, при нажатии*/\n"
"QRadioButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color:  rgb(0, 0, 0);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QCheckBox */\n"
"/* Стандартное состояние*/\n"
"QCheckBox{\n"
"    padding-left: 8px;        /* Отступ слева */\n"
"    padding-right: -8px;    /* Отступ справа */\n"
"}\n"
"\n"
"/* Состояние - не выбран*/\n"
"QCheckBox::indicator:unchecked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_error_red_24dp.svg)\n"
"}\n"
"\n"
"/* Состояние -  выбран*/\n"
"QCheckBox::indicator:checked {\n"
"    /* Выбор картинки*/\n"
"    image: url(:/checkbox_status_success/resource/checkbox_status_success/check_ok_grean_24dp.svg);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QPushButton */\n"
"/*Стандартное состояние для кнопки*/\n"
"QPushButton {\n"
"    font-size: 12pt;\n"
"    background-color:rgb(37, 41, 48);/* задает цвет фона */\n"
"    display: inline-block;                            /* пределяет, будет ли элемент обрабатываться как блочный или встроенный элемент */\n"
"    border: 1px solid rgb(52, 59, 72);        /* задает границу элемента */\n"
"\n"
"    /* задает иконку */\n"
"    background-position: left center;                            /* выравнивание иконки */\n"
"    background-repeat: no-repeat;                                /* повторять иконку */\n"
"} \n"
"\n"
"/* срабатывает, когда пользователь наводит на элемент мышью */\n"
"QPushButton:hover {\n"
"    background-color:rgb(40, 44, 52);            /* задаем цвет фона */\n"
"    border: none;                                                /* без границ */\n"
"    border-left:4px solid rgb(208, 208, 208);    /* С правой красной раницей */\n"
"}\n"
"\n"
"\n"
"/* срабатывает, при нажатии*/\n"
"QPushButton:pressed      {\n"
"    background-color:rgb(170, 170, 170);        /* задаем цвет фона */\n"
"    color: rgb(181, 181, 181);\n"
"    border: none;                                                /* без границ */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QLineEdit */\n"
"/* Стиль по умолчанию */\n"
"QLineEdit:enabled{\n"
"    background-color:rgb(44, 49, 58); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"}\n"
"\n"
"/* Если поле отключено */\n"
"QLineEdit:disabled {\n"
"    background-color:  rgba(67, 74, 88, 0); /* Устанавливаем цвет заливки */\n"
"    border: 1px solid rgb(255, 255, 255); \n"
"    color: rgb(67, 74, 88);\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QGroupBox */\n"
"QGroupBox{\n"
"    color:rgb(255, 255, 255);    /* задает цвет шрифта */\n"
"}\n"
"/* ///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"\n"
"QTableWidget {    \n"
"    gridline-color: rgb(136, 136, 136);\n"
"    border-top: 1px solid rgb(54, 60, 74);\n"
"    border-bottom: 1px solid  rgb(54, 60, 74);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(72, 81, 94);\n"
"}\n"
"QHeaderView { qproperty-defaultAlignment: AlignCenter; }\n"
"/*Цвет верхнего и левого поля*/\n"
"QHeaderView::section{\n"
"    background-color:rgb(37, 41, 48);\n"
"    border-style: none;\n"
"border: 1px solid rgb(136, 136, 136);\n"
"}\n"
"/*Кнопка в верхнем левом углу*/\n"
"QTableCornerButton::section {background-color:rgb(33, 37, 43); }\n"
"\n"
"QWidget#widget_loading_data {\n"
"    border-bottom: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QWidget#widget_processing {\n"
"    border-top: 2px solid rgb(208, 208, 208);\n"
"}\n"
"QScrollArea{\n"
"border: none;\n"
"}")
        self.widget_design.setObjectName("widget_design")
        self.layout_design = QtWidgets.QVBoxLayout(self.widget_design)
        self.layout_design.setContentsMargins(0, 0, 0, 0)
        self.layout_design.setObjectName("layout_design")
        self.widget_plot = QtWidgets.QWidget(self.widget_design)
        self.widget_plot.setStyleSheet("QWidget{\n"
"background-color: rgb(240, 240, 240);\n"
"color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.widget_plot.setObjectName("widget_plot")
        self.layout_plot = QtWidgets.QVBoxLayout(self.widget_plot)
        self.layout_plot.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_plot.setContentsMargins(0, 0, 0, 0)
        self.layout_plot.setObjectName("layout_plot")
        self.widget_plot_1 = QtWidgets.QWidget(self.widget_plot)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_plot_1.sizePolicy().hasHeightForWidth())
        self.widget_plot_1.setSizePolicy(sizePolicy)
        self.widget_plot_1.setMinimumSize(QtCore.QSize(440, 200))
        self.widget_plot_1.setObjectName("widget_plot_1")
        self.layout_plot_1 = QtWidgets.QVBoxLayout(self.widget_plot_1)
        self.layout_plot_1.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_1.setSpacing(0)
        self.layout_plot_1.setObjectName("layout_plot_1")
        self.layout_plot.addWidget(self.widget_plot_1)
        self.widget_plot_2 = QtWidgets.QWidget(self.widget_plot)
        self.widget_plot_2.setObjectName("widget_plot_2")
        self.layout_plot_2 = QtWidgets.QVBoxLayout(self.widget_plot_2)
        self.layout_plot_2.setContentsMargins(0, 0, 0, 0)
        self.layout_plot_2.setSpacing(0)
        self.layout_plot_2.setObjectName("layout_plot_2")
        self.layout_plot.addWidget(self.widget_plot_2)
        self.layout_plot.setStretch(0, 1)
        self.layout_plot.setStretch(1, 1)
        self.layout_design.addWidget(self.widget_plot)
        self.widget_message_buttons = QtWidgets.QWidget(self.widget_design)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_message_buttons.sizePolicy().hasHeightForWidth())
        self.widget_message_buttons.setSizePolicy(sizePolicy)
        self.widget_message_buttons.setObjectName("widget_message_buttons")
        self.layout_message_buttons = QtWidgets.QHBoxLayout(self.widget_message_buttons)
        self.layout_message_buttons.setContentsMargins(6, 3, 6, 6)
        self.layout_message_buttons.setObjectName("layout_message_buttons")
        self.pushButton_preview = QtWidgets.QPushButton(self.widget_message_buttons)
        self.pushButton_preview.setObjectName("pushButton_preview")
        self.layout_message_buttons.addWidget(self.pushButton_preview)
        self.pushButton_clear = QtWidgets.QPushButton(self.widget_message_buttons)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.layout_message_buttons.addWidget(self.pushButton_clear)
        self.layout_design.addWidget(self.widget_message_buttons)
        self.layout_dialog.addWidget(self.widget_design)

        self.retranslateUi(dialog_convert_graphics_to_values)
        QtCore.QMetaObject.connectSlotsByName(dialog_convert_graphics_to_values)

    def retranslateUi(self, dialog_convert_graphics_to_values):
        _translate = QtCore.QCoreApplication.translate
        dialog_convert_graphics_to_values.setWindowTitle(_translate("dialog_convert_graphics_to_values", "Перевод графика в распределение"))
        self.pushButton_preview.setText(_translate("dialog_convert_graphics_to_values", "Предпросмотр"))
        self.pushButton_clear.setText(_translate("dialog_convert_graphics_to_values", "Очистить"))
